tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
# Official Amazon AWS command-line interface
brew "awscli"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
brew "checkov"
# CLI tool to nuke (delete) cloud resources
# Modern, maintained replacement for ls
brew "eza"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Bash and zsh history suggest box
brew "hstr"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
brew "rbenv"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Tool to generate documentation from Terraform modules
brew "terraform-docs"
# Terraform version manager inspired by rbenv
brew "tfenv"
# Linter for Terraform files
brew "tflint"
# Static analysis security scanner for your terraform code
brew "tfsec"
# Terminal multiplexer
brew "tmux"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Application launcher and productivity software
cask "alfred"
# Automatic tiling window manager similar to xmonad
cask "amethyst"
# Securely stores and accesses AWS credentials in a development environment
cask "aws-vault"
# App to build and share containerised applications and microservices
cask "docker"
# Web browser
cask "firefox"
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font"
# Web browser
cask "google-chrome"
# HTTP and GraphQL Client
cask "insomnia"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Noise cancelling application
cask "krisp"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Open source build of Lens Kubernetes IDE
cask "openlens"
# Collaboration platform for API development
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Music streaming service
cask "spotify"
# Open-source code editor
cask "visual-studio-code"
